---
- name: Bootstrap Python on RHEL 8
  hosts: "{{ target_group }}"
  gather_facts: false  # Must be false because Python is missing
  become: true

  tasks:
    - name: Install Python 3 using raw command
      ansible.builtin.raw: dnf install -y python3
      changed_when: true

    - name: Link Python to the standard path
      ansible.builtin.raw: alternatives --set python3 /usr/bin/python3.6
      ignore_errors: true
      changed_when: false

    - name: Verify Python is now accessible
      ansible.builtin.raw: python3 --version
      register: python_check

    - name: Show Python version found
      debug:
        msg: "Python is now installed: {{ python_check.stdout }}"